# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/cloudrun-analytics-backend
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/cloudrun-analytics-backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cloudrun-analytics-backend
      - --image
      - gcr.io/$PROJECT_ID/cloudrun-analytics-backend
      - --platform
      - managed
      - --region
      - europe-west1
      - --allow-unauthenticated
